table 'Completed INV Correction'
	lineageTag: b5d4dc14-2134-4750-aa6c-2106b142b8e9

	column Status
		dataType: string
		lineageTag: 202f6504-4dbc-44f7-8d4c-ebcc7e3014ec
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Order#
		dataType: int64
		formatString: 0
		lineageTag: 3fdfd2ae-f34f-44fb-944b-2ea28b7f6679
		summarizeBy: sum
		sourceColumn: Order#

		annotation SummarizationSetBy = Automatic

	column 'Order Type'
		dataType: int64
		formatString: 0
		lineageTag: 21c71b8e-e860-403f-92e3-c9e8bf86d1ff
		summarizeBy: sum
		sourceColumn: Order Type

		annotation SummarizationSetBy = Automatic

	column 'Transfer to SCM#'
		dataType: int64
		formatString: 0
		lineageTag: 91c94444-ce2b-469f-ab90-68d8d1983113
		summarizeBy: sum
		sourceColumn: Transfer to SCM#

		annotation SummarizationSetBy = Automatic

	column 'Trans Category'
		dataType: string
		lineageTag: e27c1e41-c5ae-4686-b1c9-04c05a2ca7fe
		summarizeBy: none
		sourceColumn: Trans Category

		annotation SummarizationSetBy = Automatic

	column Part#
		dataType: string
		lineageTag: 8f034f46-5d13-4aab-8caa-7fac5eaa0512
		summarizeBy: none
		sourceColumn: Part#

		annotation SummarizationSetBy = Automatic

	column 'Prod Type'
		dataType: string
		lineageTag: f305ee35-b1a8-43da-990a-5ab8becfefb7
		summarizeBy: none
		sourceColumn: Prod Type

		annotation SummarizationSetBy = Automatic

	column 'Pick Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20145eca-d9db-4b4f-9009-ab57bce786d6
		summarizeBy: none
		sourceColumn: Pick Date

		variation Variation
			isDefault
			relationship: d37975ad-b1b3-4ccb-8ec3-41380678d8b5
			defaultHierarchy: LocalDateTable_f9ad4568-306e-4023-b604-711387cc7e15.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Order Qty'
		dataType: int64
		formatString: 0
		lineageTag: fe41190f-bd6d-4479-a6d5-a1efd47cc835
		summarizeBy: sum
		sourceColumn: Order Qty

		annotation SummarizationSetBy = Automatic

	column 'Unit Exp'
		dataType: double
		lineageTag: 56641857-ac15-4992-ac50-a167d5e64a70
		summarizeBy: sum
		sourceColumn: Unit Exp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Amt'
		dataType: double
		lineageTag: 09046d04-a321-4007-99ef-9613ddb27a64
		summarizeBy: sum
		sourceColumn: Total Amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'POCV type'
		dataType: string
		lineageTag: 860911c3-0e7b-44f1-bf2c-1456f14422b0
		summarizeBy: none
		sourceColumn: POCV type

		annotation SummarizationSetBy = Automatic

	column Year&Month = DATE(YEAR([Pick Date]),MONTH([Pick Date]),1)
		formatString: General Date
		lineageTag: 6c195407-facc-4627-9682-be1bd07e7991
		summarizeBy: none

		variation 变体
			isDefault
			relationship: 43adc4ca-1490-410c-8c1f-0df89ddb16df
			defaultHierarchy: LocalDateTable_dfb5917b-2cf9-421b-83d7-543662a0dad5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column KEY = 10001&"/"&[Part#]
		lineageTag: 981eef20-92ea-4798-9d77-b0f7a3811ae5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column sku_no = LOOKUPVALUE(dim_part[sku_no],dim_part[~REF_region_part],'Completed INV Correction'[KEY])
		lineageTag: a7e50a35-b9ef-4618-8149-634748bb27e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Last_pick_date = CALCULATE(LASTDATE('Completed INV Correction'[Pick Date]),ALLEXCEPT('Completed INV Correction','Completed INV Correction'[Part#]))
		formatString: General Date
		lineageTag: b841bc5d-caed-48dc-a0c0-33de25e6e444
		summarizeBy: none

		variation 变体
			isDefault
			relationship: 67fa5c5a-b4b1-40ff-91ba-fa62c70ae3e0
			defaultHierarchy: LocalDateTable_572ea3da-264f-4959-8c05-0c4d850bd700.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Completed INV Correction' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://tdworldwide.sharepoint.com/sites/BITeam_Feed_PBI_Files", [ApiVersion = 15]),
				    #"Sorted Rows" = Table.Sort(Source,{{"Date modified", Order.Descending}}),
				    #"Actual INV correction result xlsx_https://tdworldwide sharepoint com/sites/BITeam_Feed_PBI_Files/Shared Documents/HYVE PBI File/Hyve Tariff Spend vs Recovery/Recovery data from Connor/" = #"Sorted Rows"{[Name="Actual INV correction result.xlsx",#"Folder Path"="https://tdworldwide.sharepoint.com/sites/BITeam_Feed_PBI_Files/Shared Documents/HYVE PBI File/Hyve Tariff Spend vs Recovery/Recovery data from Connor/"]}[Content],
				    #"导入的 Excel 工作簿" = Excel.Workbook(#"Actual INV correction result xlsx_https://tdworldwide sharepoint com/sites/BITeam_Feed_PBI_Files/Shared Documents/HYVE PBI File/Hyve Tariff Spend vs Recovery/Recovery data from Connor/"),
				    #"Completed INV Correction_Sheet" = #"导入的 Excel 工作簿"{[Item="Completed INV Correction",Kind="Sheet"]}[Data],
				    提升的标题 = Table.PromoteHeaders(#"Completed INV Correction_Sheet", [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"Status", type text}, {"Order#", Int64.Type}, {"Order Type", Int64.Type}, {"Transfer to SCM#", Int64.Type}, {"Trans Category", type text}, {"Part#", type text}, {"Prod Type", type text}, {"Pick Date", type date}, {"Order Qty", Int64.Type}, {"Unit Exp", type number}, {"Total Amt", type number}, {"POCV type", type text}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

