table mapping_vend_inv_no
	lineageTag: 140a4c19-b822-436c-a736-11234015b768

	column vend_inv_no
		dataType: string
		lineageTag: 9e810344-59c3-42e8-9ec7-4f888ae46014
		summarizeBy: none
		sourceColumn: vend_inv_no

		annotation SummarizationSetBy = Automatic

	column vend_inv_no_V2
		dataType: string
		lineageTag: 1fc12e37-87ed-40ef-b209-053e03e0ff4a
		summarizeBy: none
		sourceColumn: vend_inv_no_V2

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column order_no
		dataType: string
		lineageTag: 09b78650-18cc-4226-a6b2-88792ed135fc
		summarizeBy: none
		sourceColumn: order_no

		annotation SummarizationSetBy = Automatic

	partition mapping_vend_inv_no = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jVvbrh23Df0V4zzHhe4X9Ck3owEatzASvwT5/98oqT2keLikgwIGLJ61NSNREhdJcf766+2XmlONZYbYfvn97Ye3R6DW298/CJxrjEVgFhzcSogKk/AeLrHkqg8nwfeOKezeMcG7Zzfvng4usQ6FSXBwmnkqTIKHezFwLw6Oo+yhkeDh0vfQSHBwmE2VyoKHR9wjJ8HDueyHk+DhFMzDU/BwMCMn4T2cZtlKZcHBrSddMRbew7GMvWIswMPHNA8fDu556GZiwcO0ShtOfmh17vVmAWAzchIcnEhVCpPgJjZyUqWy4OA2t1JZ8PPOaY98+t401d7MvLuH4zBw9GppI22tNdB57TXseXdQS0kGLtA7RqM1f75T6aF81hPOov9BzlutJABsxl5AMSXlrTcS/JoloxgSPBz6nhoJDo4l7IdHb5vItpitPGGn1zJ0t7Hg4NT3CWfBD62PrTUS/NDG2FojwQ8tm902vQGIPeY9NBL8Xh0l7r3qTVeseZ9RFvzDc5vy6AzTqiPLpKrvOVKucoD8Usbe1+I/TW9VwsxiU4I38zOlB+SmA/NYE3iaHgwyFW56cqnyTm7CY2PSx3rznPqUd1LTg2FWAf1USgzr/DxNT4YpyWgbzLPFrmD0PSttAmVJD+YkS8ZNt54jt/as54DF5u1xNQx51PKA1AQKmjLa4JVAJqoNtVbAjC+9PE1glyI9qXkwwXcDPJqA1DxQ3o3wUmpZd3wD+0SccmMUMkhDRktNsE1F3hlhKmy4bmaLNpUewTAHKL6q+gKuihxBbnr1pRJEfQl0G7ss9vQbLI0hW5ObHixTQfA1RqoKJs9bfeSgS+ZH24Mce24CXwYBqel339T1rN4nTLUVmSc1PZiSLHb155P+yb7lpgd1Vbh5oMArAeaRop4y/87c9J3UBEudZSrUPPDqh6x659Skxz7CkoWXY/Q0PViLvDNUz0nsXglheedqMbHQlefhUEp8lMBNt+OJ/dQDYMGZ49q398HCgVu0N7ILKccEEGDOa2z73ST43sPEVQk4JvbtILDg4TTrhr2nTDFD272DN+z0FxMZBe+z5V7Mu7vX+CLOPTGgTiYjM29QCxmtDQPZFxOdsODhaIZWvKdMf+nFwEiFbT+cBA/Tpt0wOAxxzA2T4JVKltGEfBDTtbrVQsKB9zaMzNfadidn8wxW6FxsN9qfrsVh2xkFFmNy3OEH0GMpzbjwxcNsohQGIxXDTDoxFnzvUHb4kSFYZW5R+MAueTvhBwem08ExcZXvXZLpXfx2WBRtwgdQajRDS/7h5FhvpbLgF7TU/fBZvCWd0QxteuNBUw1GLeB5MK9uGJm1zL1iHVi5p53aYAGUOk0M75MyqcW4N1MDt7HOHZuwcODYDQPLcjT6QSzKet4rBqzH3LVhrxYyHWWvWPfrTVZtH0EWHA/NvufNwoGmFAaiWnHV3kwQWXE8+HaJBnsP4pxx0/UcrxzN0/Ssm8WLis2zAMWv9fFQuelVOeSxh+h1FBkQNw8H/nrcY5DIipteCUliFW4eTPvVsNfWmzBO86SQypTgKQHfcILyTcIuTE82jSCB30vNEgIVvxNX5lJZCvKWKco7UwK/IGl4CbS/sq1vT3gJudbZqnj/E+in6zY5EH4v4qFy0yshNelZUfFxdtUQOgpBV8UTHi1i1LgelEDepS7ZkaZFQ0DSscse4qbn4KHvhJzsMrlXg1uzhnqQUKHIMKuz7U/ZoscbOS6fQQaEHkMWT5yb3khn2fGXdKPab8jBBnXTO5zP2qeGQD7zsfwEMc3eS1jG9UPTejOsRJ6SFuEmKCGphiDon13DkQmjnU0OEjcBlAEdnC2mbgGBuHvW5AZmz5g6PyTOD2iz6gY7Jr4VxLS3hrTJU8cirRtlUUhpgogG5yzE7RaycLB/2xUHC5iMD3Kwu9GkvFk4LLsJYACm02JuQPzQ2BIqjLaQLdqOUA5MY2JKyKjRwNq+fUkY9gUTuEGCkGxMMJHZxKudaqIEn0pYlC0wkvaiwT0xIMIyTIRSIKfHKVETDfvdklOvRi3AskRqe95IayabfrLMIZt4FnNX01wrTZ8UW3Zgw2gJQtk+58QQpEzjTIO3zCbR3L54p6Vlc8nQ4FpptH2IWPA2oaQdwDS8u2llT+yQsMrD3JcBL1UTciZMWnH60lyu+N6c61EYsj2xhKHbgQU/b5NiODimfAexfe1D8GTCXcwEDwoUTdAIOe9k1ntArnNEs6ADzHSnN5rwxy9JM/fCLHg4myuphn7ENIH6IT3Zm1lQuHMqNZroqMJVXjL3owViq5zz7p3hIo+TdmY7QEBQ8p43OJ9hmJtdFvy7k9F5BjianNEpMJhmr8HxX+GI2WsQIaVdonC4t+KrKbORT+++vrll8TG46UBOEDwgpAf6M8un6ZdC74IOeQe2KDd7spJvYv+P3HNlHq7zeECo8sg5KpjBkw8z6pUEZMVa03c2n8Imihri4Vafu111KQJCVQqT0Z2KpkZmWBVCRk9ineAtx0qrCngwShLrHKoqxit3dTZInHARg3JIt0RxRTu4ha2Lbrl5II8rdbAxuJkC4l9NGnSv+JWaknlCYqonuVQ91G+Uqtd3mKPkQgEBwZMPXS5yuXmgmhvRrFIaXTIopMm6EzALzv6tgODGhVc8lk7+5SqC0Z1wYp8r93B9jKgPq2OiBEIn3hmqPqwQYda5c06vct1zLh4REPcQ14bIZA6VIa/48QLWqCAwVRx63Rgh5/tYy6d5oKEbCa0SHzGN4In11CTF1r3PT/tKTig3HUinVyzu6yC/izXSLgw6lC/wnf+OsYCTOUg1aX93oBZLqL8PPLGqDfR6C+sNOK1jrnkwR2Vc8gIngBM0xt8Hh36a6rro87w59J1rzcEX362Upk4Mkpp0vHZvFmDeO4ArEcI/5pytc2CdZvL6p1qLNkw95IGWTG0eprVKMwWPpUE1SzTVlEilXHiyg6hD6UkzMTUmxrq5oIoQ7sdirvUiRORMjHvFkBpbMhWNMDFOVpmA/VQvYuI7SI2MYMIguNLnYoDtkkN0yPm37blCBm5WUw41IfXOdmGHImAZOIVu4juITEMzxZbAFJxsMyP3dMA1NuZqzRtnOnU7FIEjmMLcFY0Jkosrr6Yjh8wa2SVzQZV8zmm5tmbeEFOnXcB2qScx11vg84y8ex+KP7IJg05Ztmiut44+095M4DVVs1NZ8LDJwJyKOarR2itP+A4u3RRL4t1IMxH5uaTDXBLhPjfZAMj1LVLdQRTQKpcVmd0C4f7Y17gseLjvgB1dtFX7sWGo/hgm9GTBH8FmkgXgkC5yNhHaiZ4VBoJet0r7+MP55rLF/W5fIrJOye2MLJq6kdQqEJWevrxj1eQ/PaEifwXLeuh9VMmloTLaY2GoHNljWeibxKNQb6Lu5SEb24KGRZgmLlFvlrBeI74ipXTyEVZ1zqMEqM1ZHP92Y/iiodihhCRqzHQgQc6BSk/IgDJ5CwgMV7RE7lB4UjRmOnhSXAn0gFgH9NzPP00PxqY3hYdMs1aMYnESf92g6wnfNnRdskPlUdMAGQqqlg8hICq+dFX88YOJBzx8LtGLBuVeCcsy3ezSInc520DtnJtVBjt96CA2Be8fgqoPP7DgEgchCDj2zNl6eLFGSCL2kwuV9LoUvvlYGXChU8x/h6aZCQxWg8ajh9x3VFNzyITqxfmpiOS1c56mA5vuhEOKtOq95oF+mV8/ZNcrt/J3CgLiVwpaWnCoA+LEqCzZMS0qZhy8gTAl4Dz4X/z5gWxN+Phg6DsPfJj0Ehs/PFiZ1heIedZCZ8B86+UPRCXDpWRXwYqVagrgSoW79RbMV0vN7yX6i7kQbOClh2i+IwmeuohdTY1a8hYikg9pUsCQFI0mOmHBU183cPWLsUZ+HTfxs9akA1X3GWS7dp9SpT2qBesFcis83w9ne5troZXRZWDBTWZEUwM54LZ95r7T3RNKB+iBpmQObr9DNF/7BEhSsa5MNAQXFMV8RAUqIbbZjjsL3mDPXewXXw6An9htWpnOgjK7d+NozbXGoAU3qHWibuepkEUQJwWMQ856987Ng56vWk6zq+vo50mGRvYGNw8qvClwzdMcUHBwZjWpC3B2m0k+FHADlyoUBmWUaI43Cw4OYQdGLBxUudMmoExacPOxFdyqsTqNaTkp1ARGUOfZhbPRciyDejWnUY/4YcZNS5xQmcvS3uzsmu11rm3qJwMNDBKf3tvZXSb0ZkBTNLfcLBzeukNueC9byR2we5gOlsnAFK+pRRw32ljW7mbrFp/d2GyZ0ZsRXfvxthuXMm6qWFbqaqN4pjhPXsY4yPFtP/3477W36SdzTFoihuMMIVWe/X+/pwetfdDSr87kn/RM7mqhzp+ld5+FZsc4rUYK5ZVZ5o6J4+sNDOlRyX+etscNeAXYBPBtT7ZA/fbrd8FoxeuD0e4fWd5fBtv9DZR5e3+9AeM2MBkx/aQnC4Rbj6xa4TNlANFzofE2O1x9eavkFxqgCFD4tsAA7QCElEvXR4VC5GRePg89Mpd/xIMSCShVtZtS3POopbWbEnURzUItIN16qK4GmyS77LTxtuZpkAYrl9f0egCWunTZO18mb6CGg+bXDg4XrbRgtfJPtwDhVcwoHS1QZWVa4fjO9JAntszJHdPDHi977nq7zfO0lgvIhwVYgC5ZGuPdnkyXR1Vdyznevbzqy/UIp8bBT/v52wtpFOe3Vxc2czQtQXogSxX6sNgZIdYt0ovUwnaUkZ+/xhbH7KF+juXTv/786dOXX3993hpij+H12tjIPscQP0f4TR25PL/5vx4EP/rHB6+r+LqZwvvfpMOQHqtKv6l59HEYNv/s/Yja/Td0lOihoU5DCaTC1B90fcnau0VXauvRfeYKj2RQ2nDtWekSyPerM9i+tc0maA2D/ASD1s5ZPEa//fH951Zza+Xb7z8mim8D+Xqf/vjx229fvjxzWOj68W9fv/4nkaWjx1X67+vztNj5Qv1510i9Fvuu1qbOosbRQ5rfvuskWno2Jc09y+6myZAv+/ff/wM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [vend_inv_no = _t, vend_inv_no_V2 = _t, order_no = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"vend_inv_no", type text}, {"vend_inv_no_V2", Int64.Type}, {"order_no", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

