table ~glossary
	lineageTag: 7c365922-e9b8-48d0-89ba-ea6f98b7252c

	column 'Terms Group'
		dataType: string
		lineageTag: 7cbc6882-9909-4c5d-afe4-e3f1f2d533bb
		summarizeBy: none
		sourceColumn: Terms Group

		annotation SummarizationSetBy = Automatic

	column Terms
		dataType: string
		lineageTag: 8a61a5d3-e830-4aae-b6a0-86234581bfc4
		summarizeBy: none
		sourceColumn: Terms

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 5a1db141-26bf-4ee9-a0d8-88cb1d412c03
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition ~glossary = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVjdciI3Fn6VU8wNTAzGf5PEKV9gzNieHQxlsCeuYQrkbgHa6W51JDWEvZrXSFX25eZJ9hypu91gmoyTze6Ny0g6f5++86P++LHSZoGXBMxweC9nwqvsVdoyMkoGAfdhuIo5rgxiHvmnlU972457iTZjT/p8PFMyiXGlDpPL99CVCw69KFhNoD5Kms0jDq9fW03Af/WCRAsZvX5dorTPlIH3fMEDaEttoGWMEo+JQRlr4EZG9cmHXu/iYQLkgAy5Kpih7Q9S+iuwBkvN9C66Vt05n0rFYXLYPGzWD5r15kHRaaepAIv1brfmtgxD6QuzgssclS4z3pxrYLCmEWJS9xfNZZewGc4bjMWGwxD3SKaWrcWQ3CnYvVrhhe0ye8GnIhLpHTxwpkj08E0XRebW7lslw3WrMloy5X+D8QuhuGfQ6nmyKo3SyV+2+hp/lJyxUaRHbrmHJFSrMuoiTWBNZ90FPTlp/oDOL4WZw8QwJabTCYgIzJyDz7WnREwogFQgDA//CMPMjdK4Wp6XhLQkUHooDQvgksVFh46ab04mZI9cO/xTrm2n1YZva1csIsOVJ8N4vEASjKcBm61h9OPRpOQGd6plnrfPvBhyfa0gAIkBKPCYxvx40pmpeVYx1hRuFBVcecdCETBLz+81YAghj8zZqFIsS6PKjohZtMrivb4Zdm7bvXav22/dPJxK5XM1tkUvYiFH5ZFhItIwqlw93HdGFUt24cWLWDrcth8bqVE0aF12XqbQHcZUEhqiJAieh/AcMlw8aMB1ITQY9Fzqur9WKXiRAQf82SHEuNDu975rac0NDNlsFB024JdEImsDEXFLLg1nQJnyEwDx8yf6cWi9JW7sAdbr9BwxEwuAgUceyGgGRoLjbmMUHTWwSnBg1pJhMwrNCOQRHsKkMCIOeObw93qPmO7oLgNym2QHPUwIJNEjd1H73G9AlWIgYiQa/+n3AHzKuX06jWxAhOxvtOJzhCbEJFrOBRYl3I+4s59qq5XkLVrwUBWb8bGcjg0l7vgRKYyVWBvct0jZZaAVtA2xLCyUdlSlUO1Yf07GDqZxLL0F7jhRtwaKZKZUctvXA3tjg3/cvWoAMasfaMKbopgzvIUpaOIWHoA500+4FlQ9IbvK0WQ+whc3Svx0ecdCmUQUrU5CkFP4OAvGLEQyy7GfxIHwUOTTc55Sx4K+kjPFwmKpJu9nyARKCIjdvovyHBSPJZYeCtVy9hUdtolkBxT6jzVG5nKr+BXG9PXLbxoCiS5RjQxZHAtk40Iw0HMR043nm9UPhIZVQ30VqW7HjRSlJeYpi4hasKS66ti5ZrXWIH8eS/25vrn/37rioSvtXIlNdS+ttI8Biz6n+khRbsuxyUfJHhXopdDIk7sIk1XMIu7bax06DmETUwkL8C7TBTv4AE4iMEjiOFhR6UdF2D2Q3NghMC0X/BQG7a6tI8fNk5MfoJ4V/wULEgqVth8Z+ufxDM8+XjaBdR1hfTVSUVdT1HwQLH1qgVX8l4RjDET2R45RabKJoPbvbsFwFrrqRCUJMfK41tRE9UpTz1xx03juCKn1cjtIe5OBasMTlH/oazX/dd27rZ0CtQAwOEejiq9ffj+swT2uICjovRQe//rl39Sscat6XIOu+BVzFiWx7O+CArAL70IB9+l0n62o88EV1kqoDiXi4iconScmUsdlNQrVsqtej8eONJuxrLHnBWHR8v8lLk5xbUg67lHyYKnD0uQTB6jCUeakXqQF0ijmfeaqQIvc+42TyIu/LYhpY3h+cQot7OBuXtLCJHb7jxPRTQHbki9KwkfUhW03TUIyhd1+J61tSVrYK8/GLEsM1FJ9RgZiwjq7le37pUS736rYDhBUqaA4vZR4QYe/xRVaWEeBJAtIHDfghajbJm1bkn3Jult2bdKV/lY/v/yhIxbSD7vxdzlv4lwqFck2RE6olG8ijStl6HaXWveXYJ9pwSp3rOAm+GIhfAjpBN6fFpSJ+Iw72W8eU9FMBxJ3oLbdRLc3sBQbGUuNYk6fNdfuiy1mThM6o635M2juASo4azYc92y7cc2mqGh/i2zVzUQZYJjBiG4KBgpk8FghmnHL3Ucz3mf6hoFaPRlI5VKGdly5QyftOhm55X6aJlaSmyV1mWb9oHDmUuFaSvXiqYP6UeHUAw8CuUyZlhvjUDzTUwyHol10o+70VGLcBwgc8GgCXN8qkOzZBi10WcSSAFr+P3EGIEhLGNXP6pbbuRA6TgxOynuVu6geM5ENhu6p6rvt/waXb3CaSn9BKzQ5AtlaarYOpQjUyxCovwSBGb7QqxE6w1LDC+0oWXvuJGouVoWt+lwmuoheUjSWlG4ZcvZJkxKoebzfPNinNN5ucCN4tFz1Mshq+WNjY+zBAd896fKj2deHdHhKf8VMm0YJdVJcHNoFmL/hJrfe4tris9srpsX21H/XgWrHvvQyTjwFTEBcMINTuUzwsUf9wd7GUM5VkvWckEXkb/o8maYdJdH4MGxk33Pe21petbeV6jqDd53xeWvYvtrHf247953bQWf/7d3Nxfjnt53bGmA4u1j8ArKiP+NzV0XHIhp3mfLmbjkvrtYzyx/68EE1+Wj/aBd/Og799VxcJ33Oafy/rGL8/Zl6y5lGmbb7PCqVmInIvsD9tCANUMKwjduk5HLPn+spEKcVz05EEnItyim3yujTB5F/7ZlgOYy0CeiRga9xrP/NZvrWEiZTOarcSKCvLVpTIKNKY6tlFm21XHi6CawaGgohN6DwdCsaxKlmVPYVVeTTEj6z6UN5bEQo/sVteAEdsjRX3CjBF3b8xY01qVf2RPGLmltPE4jOXw9xliIPMc4t8jiZu29GqAmb8h74fIr3bd9xiX4yumkhneUqnz79Bw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Terms Group" = _t, Terms = _t, Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Terms Group", type text}, {"Terms", type text}, {"Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

