table ~glossary
	lineageTag: 7c365922-e9b8-48d0-89ba-ea6f98b7252c

	column 'Terms Group'
		dataType: string
		lineageTag: 7cbc6882-9909-4c5d-afe4-e3f1f2d533bb
		summarizeBy: none
		sourceColumn: Terms Group

		annotation SummarizationSetBy = Automatic

	column Terms
		dataType: string
		lineageTag: 8a61a5d3-e830-4aae-b6a0-86234581bfc4
		summarizeBy: none
		sourceColumn: Terms

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 5a1db141-26bf-4ee9-a0d8-88cb1d412c03
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition ~glossary = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVnrchpHFn6VU6i2CiUSICTFiVL8QEBkbAsogeWojItqDQ2a9TA9mQsy+eXX2Krdl/OT7He6e4YBBkXabHZ/SKXp7nPt79xaHz+WWsJzEk/Ekt6pueuUjkot5ceh8jw5pdEqkFi5kY5aynB1MfZfr5aS1icuPjpJFE8cNZWTeaiS4FNjXPrQ77fvxqVxUqvVfzC/PdeX5MZyETXOaz+e7GxNZeSQA7bC9WlcGonQnc3Awu/fjP0PSk1Xf07oae2H85cJ/Y8Mqz8t46+R+tPpn5HaUz5pB+96lRmeOvq3XKvhDwPpT4ugIBynKpyAZp6Ys+K9TaXX/HNWkbX7BbSX75q9t+XDAlxsM7l7ngJrF4RyAf+4/rz06agoNLY8hJW5jGlrlWahWtDUXUx4Qy1kSAF+PkZKL0x89WkP+4EIY3onl9KDVVFMzTgO3fskdpWPXVEZxx8epE+DPj2IiE74D77ciJTvrY4oYHJPkztMLtbk1CAVTqGF2Z57JBbxEfmKfIk4jxVNlSG6D6VwPk/Vo1+hzhexCDwJOQf12snJq/PKOBz791t6LBIvds0xo84Fn3Jxavj2PbX6ffCWkf/t6z/iDIHfvv6z1fv29V80UyEJz8toKwV60nfsQEeCdC4najaJVSy8yb2I5ETrXNYLBui8UCWzAKb8ebhhCdVPfjw7O9WmuFpLXBGlqm4reLFJWj89++mVJj3J2eerzLKIWj0bMbnff3A1Nc2xnuOY46a9yXf/Gr4e9Fu3BPWiVYToB6kxNFBr4+EtPvW39Kp6aouqiOi7WqV+zhSnrESyIDWj+EGmJ5/QHmwP6pmO3dkzSIqxGDOkAMhZEuJPoMIx/CMK5W+JG8pphr5nSclnr30C6VFSEhVt/3nMsbJnlRTYRr+GuWlRoedDp4nKCx02dLx6Bx1V4sc6s2Qi/Ni6iJ7ENO1KyQmpVCp70lO/fY3f7oyGSRB4LiQ3qH3Xaw5Hd9R6Pxz1r4d0edN/27mxt+nG9OgiuO8ltVe+iGIkKcWX++hGMr877P26R2ZLLRZq6sYrurIZF0l+Ei3DCSd5KHC3K6vZav1MUBOlYOI/PnGw9yE7x0jSJ/dwHFSon2p+tMEDUIPAKo7sMyEtD/j7kRln9QJa3XvC/8xB1B3RVMSAVxoKg8uuESLg7BVEeeqRPOZ5QWkCYtakOQWhWrpTpPL7FV12hy2KpVikWaXg2GvmvHQFDfsHgG6InI+yBzhWaYnyjpTtHFTShJCjx6U/6rLLJQfqOIKDrUIG7ePYusJEZr74GjJTAbWzEer5ENWO2PW8rstakXMT+JpB9DlJa2nj/PzsrHbyFOUPoHzbuWsgkcw5M3yfmcj5BrUvSEDiZEbq+j0uhXImQ+k7uP4B3XZ6bWr3W+OSZokaEAM5SB8PYpnGpq+OdDbhxJKucGR+Zhngob0swwrBjGwf+c2HeKt/HK7Agm9irV3KgdlucYG5jvA5h0SxNZtP434f3fghd/qIVdWembk+6u0qU5RdgRrs+kvlwlQ/WdyDuYZyW+Kwa7uPOylCc5PXSCcPWNF9IC34q4GEBEl+ZJN2G/hnN6WDgz017FP04AYMdLknWExPd9UcRNlHbh7RDVLGtGlS4DEVnzP6mUN7pOkW1grbamf3ySo89gxRWZOZylsv7ApZ7z2Dc9NxkgUvudBspIvQlQhYBKvIWEJPui7mc97buV7Xj1Hu1CKYMCB0JsRqoMynLxZyXaYQS4jmcBohf42139BGA0MYK9o0XPm+/DIu7YrId+emjnzkOM7nc9u0MzO7l2Vwu5XfyXK23bMxZPK9WWEQqnXeTnODni8KQG68Lb84HoJQr7wRC9cTGvivIrhgsUBLAOYA/DUujfpIg0XGZv4U/ir1Zrc36ty0+q3+9aDZu7vQKcCmsQ3/wqd3tx24QUAZ1wmWxdeQHmMbh82rzssYmsPrBLRrQgbLvD9OkHdypqF85JO8yWroQ2yL0ajritEa9L9vRihtNBJzLkn0W6JiSesxFkjid4GfiXhS/5k/6lpbHm+PCC2dPafnWE54XA8Bbc6LepatcKlCVZIktCT0bWxa7JrxJhtSrMKvojTjcrL2WG2mRYZKMaKtRqmsUJltYGAgZ+puSycwqvJpoAEe0t88REm4ZoFq/vjgOg+8n45Xltvhnhh+stfEvvaUiV/dSFaJ2/f1wt55NUQFM/XSuGkSKGeJHUNq1ihkGl31Wt2hvjG0jgemqA+8iP3NVjyImNulSNjecmP4y7Fae3aVeVNM4b5gX2dp4s60tPiMzADyce5N0IoDpJNpgoYTvYb8tItT3Z0MQjUPxWLjsQrap+M5Nz68b6y8RCcQqNB0zxqzB3xYB5J53LDjzFUhOfdOmGajrP2hBXo0TrTcUOkKx2U73Sx/SJs+sk2ffnqwXkJdRgnX5Vh3SAadG1IPs8GnWJ9u7/Z/q4qz0RNuDFr5No4ZZbIMmjDDxbk++j2Ggsid+3Kqr9W8ShEKWpgID3dpF67Mswpyv548VvYxBKUX4Eb5RFgu5QUNW9c6j5zVzs9/pONjq9JSeAmbytv3Avo5MvXnAJfNzur6yK+xCrmJQMToJia60I7l4VPCBgb7vYRVEcuEUwfvb3STbbITpyT4yJFRlJvPVzKu7CrCbJ1MDk+bqVOzwYp1LWdf3f7N4YVpWuNVwCwwytUP6db0bl3Tu/Fkhy9slc8O6dr9gpgFJdL+U65At/GkF7DPpwdixZWPXiNXUnmk4JdpAuosMAEdE9UgOkyvetMe3Tpt27KBnheYxcv/F7sk27VFabDHwYNUh9Q0ZQxwhuPIsVrYBJm175nymfZbJ/kV4q8yYlYZXbYvqIkKrtsjitw40dt/HIimCygKPjM8cNm1QWgGUHoS1jolmSkkbbM0MMClvAMGRsImuvWISnuBdlvIWDcQevLeGFGLteDDz1GFFza9wJQ5T5xV6IVe10ValyT9Omxu2b786NSPCS9dHhlgAX6oxt9nuAkyKkuSbrgZoCze0hHQIrRYpebtFekB0FtliuXUpKm7dO1QiPvDJAuG9Vr9vFo746RpGxJz4LBYxHV/qCFmX5nzMd2obdyXWM4NJygTafENqh0RGDTWT6ooN6bY5BlVC2jL6ZuicRgieD0/gyB1jybiHne/+hDjfOb/BYCrozwVmpDhHZPuoKReZyE3cmrDRFPK+JGrTO34JHfmKsSahXr+1Mnxae7UnfQ89WiRlgmTlD/Tx5Q+l0/BjavTOsWYJzg0eNwBbm7lQLazwQvXwheJR83p39EDsEv3IGqQ5i2z03ajIInRKR+V3vvHgXDTxtC8aUzN9n8Dyz10U/YLE3aceSBdE+k4vtcDx/s8cPwSD/BEXvahjLCCl5GB5OGukuCczwqF/NI3g/iFSUM/Tqae0yONBVDtrFo7qXIYFwvcMh6Sy07qssNs2Nhqe9TMjnTZUcYnj2O2ebJfgYjiyh7oWL8Yb+fc/IybLLzFjcWd28uHRXHov+lQuaMnvRQTa4PZEW0RoytXCYY9rg/6NkbqIUzSmrMQPutrx5OZrShJhMGwkr7tvNO5vKxvy/Jq0JvO5LI5ar2u4o+bzm3nZtip/vK+1578+kvn5pBgzlMofgFYoc/k0mTRietPrkXoPJjlLLlqzTR+7NN77bR6+hR+Osb7m7G4CfoM0/h7X8b46yP1RooINC3zmK9Cd86vqblX4yEoYrF1mxxcZvzpzogxHcr0hK8o4xIa5poZP30w+DfGBI1hwMbjIQPTOPJ/rZY9fKcsx6WeIn5tiSI2xD5Y70gGdZHk3OjmImtElDN5618ga4Hoauwb2O5o72bdEsZs/idSELsL93fz+Kz/naFhHso4dOVSt7/Y2KA60CfyL2pm3QYQn++O0Euxht1ZEb19JOfmnIvyEU3lDPet5zjz3G6ItiXYXq706dO/AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Terms Group" = _t, Terms = _t, Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Terms Group", type text}, {"Terms", type text}, {"Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

